dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - py.test --doctest-modules esy -v --cov esy --cov-report term-missing tests --cov-config=.coveragerc-travis
  - cd docs; make html
after_success:
  - coveralls
jobs:
  include:
    - stage: deploy
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: docs/_build/html
        on:
          branch: master
